<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>txt</string>
   </array>
  <key>name</key>
  <string>scl</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.scl</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(^\s*\?)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*&gt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#text</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>comment.line.number-sign.scl</string>
        </dict>
       </array>
    </dict>
    <key>expression</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expression__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expression__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expression__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(AND|OR|WHERE|MAP|AS|NOT|DATE|LENGTH|LOWER|UPPER|KEYS|LATEST|MAX|MIN|SUM|MEAN|SORT|GROUP|JOIN)</string>
          <key>name</key>
          <string>keyword.operator.scl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\+|-|\*|/|%|=|!=|&gt;=|&gt;|&lt;=|&lt;|:|,)</string>
          <key>name</key>
          <string>punctuation.scl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}:\d{2}Z)?)</string>
          <key>name</key>
          <string>constant.character.scl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\d+(?:\.\d*)?)</string>
          <key>name</key>
          <string>constant.numeric.scl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&quot;(?:\\&quot;|[^\x{0022}])*&quot;|&apos;(?:\\&apos;|[^\x{0027}])*&apos;)</string>
          <key>name</key>
          <string>string.quoted.scl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(NULL|ONCE|THIS|INDEX|ID|NOW|TODAY|DAYS|HOURS|MINUTES|SECONDS)</string>
          <key>name</key>
          <string>constant.language.scl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:[_a-zA-Z0-9]+:)?[_a-zA-Z0-9]+)</string>
          <key>name</key>
          <string>variable.other.scl</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>expression__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>expression__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>expression__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>illegal</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([^\s]+)</string>
          <key>name</key>
          <string>invalid.illegal.scl</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#statement</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#option.text</string>
        </dict>
       </array>
    </dict>
    <key>option.text</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(&lt;&lt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#option.text__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&gt;&gt;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s]+)</string>
          <key>name</key>
          <string>string.unquoted.scl</string>
        </dict>
       </array>
    </dict>
    <key>option.text__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>statement</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(BLOCK\s*)([_a-zA-Z0-9]+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.scl</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#statement__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(INSERT\s*)((?:[_a-zA-Z0-9]+:)?[_a-zA-Z0-9]+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.scl</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#statement__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(SHOW|WATCH|LISTEN)(.*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.scl</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#statement__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(IF|ELSEIF|WHILE|SWITCH)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#statement__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(ELSE)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#statement__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:((?:[_a-zA-Z0-9]+:)?[_a-zA-Z0-9]+)((?:\[.*?\])*)(\s*:?=\s*))?(ASK\s*ANSWERS?\s*(?:SHOW)?)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.other.scl</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>keyword.control.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#statement__6</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:((?:[_a-zA-Z0-9]+:)?[_a-zA-Z0-9]+)((?:\[.*?\])*)(\s*:?=\s*))?(ASK\s*(?:TEXT|DATE|NUMBER))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.other.scl</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>keyword.control.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#statement__7</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:((?:[_a-zA-Z0-9]+:)?[_a-zA-Z0-9]+)((?:\[.*?\])*)(\s*:?=\s*))(FETCH\s*)((?:[_a-zA-Z0-9]+:)?[_a-zA-Z0-9]+(?:\s*,\s*(?:[_a-zA-Z0-9]+:)?[_a-zA-Z0-9]+)*)((?:\s*OF)?)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.other.scl</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>keyword.control.scl</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>variable.other.scl</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>keyword.control.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#statement__8</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?:((?:[_a-zA-Z0-9]+:)?[_a-zA-Z0-9]+)((?:\[.*?\])*)(\s*:?=\s*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.other.scl</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#statement__9</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.number-sign.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>statement__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>statement__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>statement__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>statement__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>statement__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>statement__6</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>statement__7</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>statement__8</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>statement__9</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>text</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(&lt;&lt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#text__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&gt;&gt;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.scl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s]+)</string>
          <key>name</key>
          <string>text.scl</string>
        </dict>
       </array>
    </dict>
    <key>text__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
